version: "3.9"

services:
  app:
    image: backend:v1.0.0
    build: 
      context: .
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: backend